function createhggroup(Parent1, XData1, YData1, XData2, YData2, YData3, YData4, XData3, YData5, XData4, YData6, XData5, YData7, XData6, YData8, XData7, XData8, YData9, XData9, YData10, XData10, YData11)
%CREATEHGGROUP(PARENT1, XDATA1, YDATA1, XDATA2, YDATA2, YDATA3, YDATA4, XDATA3, YDATA5, XDATA4, YDATA6, XDATA5, YDATA7, XDATA6, YDATA8, XDATA7, XDATA8, YDATA9, XDATA9, YDATA10, XDATA10, YDATA11)
%  PARENT1:  hggroup parent
%  XDATA1:  line xdata
%  YDATA1:  line ydata
%  XDATA2:  line xdata
%  YDATA2:  line ydata
%  YDATA3:  line ydata
%  YDATA4:  line ydata
%  XDATA3:  line xdata
%  YDATA5:  line ydata
%  XDATA4:  line xdata
%  YDATA6:  line ydata
%  XDATA5:  line xdata
%  YDATA7:  line ydata
%  XDATA6:  line xdata
%  YDATA8:  line ydata
%  XDATA7:  line xdata
%  XDATA8:  line xdata
%  YDATA9:  line ydata
%  XDATA9:  line xdata
%  YDATA10:  line ydata
%  XDATA10:  line xdata
%  YDATA11:  line ydata

%  Auto-generated by MATLAB on 03-Jul-2015 11:55:11

% Create hggroup
hggroup1 = hggroup('Parent',Parent1);

% Create line
line(XData1,YData1,'Parent',hggroup1,'Tag','Upper Whisker','LineWidth',0.5,...
    'LineStyle','--');

% Create line
line(XData2,YData2,'Parent',hggroup1,'Tag','Upper Whisker','LineWidth',0.5,...
    'LineStyle','--');

% Create line
line(XData1,YData3,'Parent',hggroup1,'Tag','Lower Whisker','LineWidth',0.5,...
    'LineStyle','--');

% Create line
line(XData2,YData4,'Parent',hggroup1,'Tag','Lower Whisker','LineWidth',0.5,...
    'LineStyle','--');

% Create line
line(XData3,YData5,'Parent',hggroup1,'Tag','Upper Adjacent Value',...
    'LineWidth',0.5);

% Create line
line(XData4,YData6,'Parent',hggroup1,'Tag','Upper Adjacent Value',...
    'LineWidth',0.5);

% Create line
line(XData3,YData3,'Parent',hggroup1,'Tag','Lower Adjacent Value',...
    'LineWidth',0.5);

% Create line
line(XData4,YData3,'Parent',hggroup1,'Tag','Lower Adjacent Value',...
    'LineWidth',0.5);

% Create line
line(XData5,YData7,'Parent',hggroup1,'Tag','Box','LineWidth',0.5,...
    'Color',[0 0 1]);

% Create line
line(XData6,YData8,'Parent',hggroup1,'Tag','Box','LineWidth',0.5,...
    'Color',[0 0 1]);

% Create line
line(XData7,YData3,'Parent',hggroup1,'Tag','Median','LineWidth',0.5,...
    'Color',[1 0 0]);

% Create line
line(XData8,YData9,'Parent',hggroup1,'Tag','Median','LineWidth',0.5,...
    'Color',[1 0 0]);

% Create line
line(XData9,YData10,'Parent',hggroup1,'Tag','Outliers',...
    'MarkerEdgeColor',[1 0 0],...
    'Marker','+',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create line
line(XData10,YData11,'Parent',hggroup1,'Tag','Outliers',...
    'MarkerEdgeColor',[1 0 0],...
    'Marker','+',...
    'LineStyle','none',...
    'Color',[0 0 1]);

% Create text
text('Parent',hggroup1,'VerticalAlignment','bottom','Units','points',...
    'String','MRD-',...
    'Position',[187.208725393701 -13.9889763779528 0],...
    'HorizontalAlignment','center','Size',30);

% Create text
text('Parent',hggroup1,'VerticalAlignment','bottom','Units','points',...
    'String','CD19-',...
    'Position',[561.626176181102 -13.9889763779528 0],...
    'HorizontalAlignment','center','Size',30);

