function S=calc_D_stats(D,rc)

nms={'Mean','Std','CV','Median','MAD','Min','Max',...
     'Prctile 5%','Prctile 10%','Prctile 25%','Prctile 50%',...
     'Prctile 75%','Prctile 90%','Prctile 95%'};

if is_col(rc)
  x=[ mean(D.dat,1); std(D.dat,0,1); std(D.dat,0,1)./abs(mean(D.dat,1)); ...
      median(D.dat,1); mad(D.dat,1,1)/norminv(0.75); ...
      min(D.dat,[],1); max(D.dat,[],1); prctile(D.dat,[5 10 25 50 75 90 95],1)];
  S=make_D(x,nms,nms,D.sdesc);
else
  x=[ mean(D.dat,2) std(D.dat,0,2) std(D.dat,0,2)./abs(mean(D.dat,2)) ...
      median(D.dat,2) mad(D.dat,1,2)/norminv(0.75) ...
      min(D.dat,[],2) max(D.dat,[],2) prctile(D.dat,[5 10 25 50 75 90 95],2)];
  S=make_D(x,D.gacc,D.gdesc,nms);
end

