for i=1:slength(list_of_bams)
C.command{i,1}=strcat(['bsub -q week -M 5 -o stdout',num2str(i),'.txt "java -Xmx5g -jar ~/Projects/Tools/GenomeAnalysisTK.jar',...
 ' -R /seq/references/Homo_sapiens_assembly19/v1/Homo_sapiens_assembly19.fasta -T DepthOfCoverage -o ',list_of_bams.sample_id{i},...
'  -L /seq/references/HybSelOligos/whole_exome_agilent_1.1_refseq_plus_3_boosters/whole_exome_agilent_1.1_refseq_plus_3_boosters.Homo_sapiens_assembly19.targets.interval_list -I',' '...
,list_of_bams.clean_bam_file_capture{i},'"']);
end