function dRanger_output(fname,trans)

lanes = load_lanelist;

nt = length(trans);
for i=1:nt
  tsupp(i) = length(trans{i}.support2);
  nsupp(i) = length(trans{i}.normal_related_pk{1,1}) +...
             length(trans{i}.normal_related_pk{2,1}) +...
             length(trans{i}.normal_related_pk{1,2}) +...
             length(trans{i}.normal_related_pk{2,2});
end

f=fopen(fname,'w');
fprintf(f,['Id\tExample\tEnd1\tChr1\tPos1\tStrand1\tEnd2\tChr2\tPos2\tStrand2\t'...
        '# support\tnormal support\t'...
        'related support ++\trelated support +-\trelated support -+\trelated support --\t'...
        'normal support ++\tnormal support +-\tnormal support -+\tnormal support --\t'...
        'DB1\tDB2\tGene1\tGene2\tSite1\tSite2\n']);
for i=1:nt
  st1=chrpos2genomic_location(trans{i}.end1.chr,trans{i}.end1.bp2);
  st2=chrpos2genomic_location(trans{i}.end2.chr,trans{i}.end2.bp2);
  example_fle = trans{i}.annotated_support(1,17);
  example_id = trans{i}.annotated_support(1,6); 
  idx = find(lanes.FLE==example_fle);
  example = [lanes.FC{idx} '.' lanes.lane{idx} '.' num2str(example_id)];
  fprintf(f,'%d\t%s\t%s\t%d\t%d\t%d\t%s\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%d\t%s\t%s\t%s\t%s\t%s\t%s\n',...
          i, example,...
          st1{1},trans{i}.end1.chr,trans{i}.end1.bp2, trans{i}.end1.strand,...
          st2{1},trans{i}.end2.chr,trans{i}.end2.bp2, trans{i}.end2.strand,...
          tsupp(i),nsupp(i),...
          length(trans{i}.related_pk{1,1}),length(trans{i}.related_pk{1,2}),...
          length(trans{i}.related_pk{2,1}),length(trans{i}.related_pk{2,2}),...
          length(trans{i}.normal_related_pk{1,1}),length(trans{i}.normal_related_pk{1,2}),...
          length(trans{i}.normal_related_pk{2,1}),length(trans{i}.normal_related_pk{2,2}),...
          num2str(find(any(~isnan(trans{i}.annotated_support(:,20:19+(end-19)/2))))),...
          num2str(find(any(~isnan(trans{i}.annotated_support(:,20+(end-19)/2:end))))),...
          trans{i}.end1.gene, trans{i}.end2.gene,...
          trans{i}.end1.site, trans{i}.end2.site...
  );
end
fclose(f);
