function t = standardize_type(t)
a = {'Missense_Mutation','Nonsense_Mutation',...
   'frame_shift_del','frame_shift_ins','in_frame_del','in_frame_ins',...
   'nonstop','silent','splice_site','splice_site_del','splice_site_ins','Splice_Site_SNP',...
   'Splice_Site_Indel','Frame_Shift_Del','Frame_Shift_Ins','Silent',...
};
b = {'Missense','Nonsense',...
   'Frameshift_Del','Frameshift_Ins','Inframe_Del','Inframe_Ins',...
   'Nonsense','Synonymous','Splice_site','Frameshift_Del','Frameshift_Ins','Splice_site',...
   'Splice_site','Frameshift_Del','Frameshift_Ins','Synonymous',...
};

for i=1:length(a)
  idx = find(strcmpi(a{i},t));
  if ~isempty(idx)
    t(idx) = repmat(b(i),length(idx),1);
  end
end
