function [S,RS]=glioma_diff_analysis_step(D,C,N,force_in_0)

if ~exist('force_in_0','var')
  force_in_0=zeros(1,size(C.dat,2));
end

RS=zeros(size(D.dat,1),N);
for i=1:size(D.dat,1)
  [pzz,S(i)]=differential_analysis(reorder_D_rows(D,i),...
                                   find(abs(C.dat(i,:))<=0.1 | force_in_0),...
                                   find(C.dat(i,:)>0.1 & C.dat(i,:)<=0.9 & ~force_in_0),...
                                   struct('method','medmad_zprctile_all','prctile',90),...
                                   1);
  if N>0
    [tmp1,SR,tmp2,tmp3]=... 
        differential_analysis_permutations(reorder_D_rows(D,i),...
                                           find(abs(C.dat(i,:))<=0.1 | force_in_0 ),...
                                           find(C.dat(i,:)>0.1 & C.dat(i,:)<=0.9& ~force_in_0),...
                                           struct('method','medmad_zprctile_all','prctile',90),...
                                           N,0);
    RS(i,:)=SR;
  end
end
