function gsea_aravind(D,supid,compst,gene_set_file,rpt,outdir)

cd(outdir);
gctfile=[rpt '_input.gct'];
clsfile=[rpt '_input.cls'];
write_mit_gct_file(gctfile,D);
write_mit_cls_file(clsfile,D,supid,1,1);
minsetsize=3;

unix_str=[ 'bsub -J gsea' ...
           ' /usr/java/jdk1.5.0_06/jre/bin/java' ...
           ' -cp /xchip/projects/xtools/xtools.jar -Ddebug=true' ...
           ' -Xmx1800m xtools.gsea.Gsea' ...
           ' gsea -param_file ~/gsea/gsea.weighted.prm' ...
           ' -metric Signal2Noise' ...
           ' -rpt_label ' rpt ...
           ' -gmx ' gene_set_file ...
           ' -res ' gctfile ...
           ' -cls ' [clsfile '#' compst] ...
           ' -set_min ' num2str(minsetsize) ...
           ' -out ' outdir ];

disp(unix_str);
unix(unix_str);

