-----------------------
   TABLE OF CONTENTS   
-----------------------
A. Breakpoint localization
B. Comparison with SNP6.0
C. False positives

--------------------------------
   A. BREAKPOINT LOCALIZATION
--------------------------------

A1. OV-0751 chr4 intrachromosomal deletion
-----------------------------------------------------------
  A1.1)  5 READ PAIRS span a ~45.6 kb deletion in PPP3CA
-----------------------------------------------------------
% Diagnostic plots are generated by the Matlab script
~/CancerGenomeAnalysis/trunk/matlab/segseq/doc/example/OV0751_chr4_deletion.m
-----------------------------------------------------------

[Read name]                           [Left]        [Right]   [CIGAR] [Qual]
30VUWAAXX090325:6:36:1629:983#0	  102212312(fw)	 102257878(rc)  101M  73
30VYHAAXX090329:3:6:339:532#0	  102212312(fw)  102257878(rc)  101M  84
301V3AAXX090328:6:11:863:1557#0	  102212374(fw)  102257937(rc)  101M  68
30W1WAAXX090321:8:90:243:1605#0	  102212382(fw)  102257922(rc)  101M  77
301V3AAXX090328:7:1:30:612#0	  102212384(fw)  102257919(rc)  101M  74

LEFT breakpoint occurs to the right of 102,212,495
RIGHT breakpoint occurs to the left of 102,257,878

      		[Left bkp]   [Right bkp]   [p-val]  [Normal reads] [Tumor reads]
Funny reads	102,212,495  102,257,878
SNP6.0		102,210,583  102,257,809   <-- MOST ACCURATE
SegSeq 30W1W	102,214,475  102,256,744   pval 7.8e-33  464 N, 246 T
SegSeq 3023J	102,215,064  102,259,258   pval 2.8e-15  400 N, 126 T


-----------------------------------------------------------
  A1.2)  FLUCTUATIONS in the density of aligned reads
         may bias breakpoint localization
-----------------------------------------------------------






A2. OV-0751 chr18 intrachromosomal deletion
-----------------------------------------------
6 READ PAIRS span a ~508.3 kb deletion in LOC647946

[Read name]                           [Left]        [Right]   [CIGAR] [Qual]
30W2LAAXX090326:6:45:1245:382#0	    35115275(fw)  35623700(rc)  101M  78
30240AAXX090405:5:50:743:74#0	    35115318(fw)  35623681(rc)  101M  77
30VYHAAXX090329:5:97:467:963#0	    35115345(fw)  35623782(rc)  101M  84
30W1WAAXX090321:7:91:1083:610#0	    35115360(fw)  35623808(rc)  101M  79
30VYHAAXX090329:3:17:791:1919#0	    35115364(fw)  35623794(rc)  101M  81
30W1WAAXX090321:5:47:621:1176#0	    35115385(fw)  35623745(rc)  101M  80

LEFT breakpoint occurs to the right of 35,115,496
RIGHT breakpoint occurs to the left of 35,623,681

      		[Left bkp] [Right bkp]
Funny reads	35,115,385 35,623,681
SNP6.0		35,118,156 35,620,642	Copy number 0.82
SegSeq 30W1W	35,122,257 35,626,717	Copy number 0.79
SegSeq 3023J    35,114,514 35,623,052   Copy number 0.71  <-- BEST PREDICTOR


--------------------------------
   B. COMPARISON WITH SNP6.0
--------------------------------

/xchip/tcga_scratch/ng/OV-0751/snp6/OV-0651_COTES_H06_after_5NN.seg.txt


--------------------------------
   C. FALSE POSITIVES
--------------------------------
We can assume that predicted breakpoints with ratio changes < 0.2
   represent false positives.  However, since p_merge is based on the
   number of reads, there is not a one-to-one correspondence between
   p_merge and the copy-number ratio change

--- Picking p_merge ---
SegSeq -s test_30W1W -t OV-0751_30W1W_noCNV_aligned_reads.mat -p 1e-10 -v 0
p_merge  1.00e-10	0.506 of 478 breakpoints with ratio changes above 0.20
p_merge  1.00e-13	0.566 of 401 breakpoints with ratio changes above 0.20
p_merge  1.00e-16	0.592 of 375 breakpoints with ratio changes above 0.20
p_merge  1.00e-19	0.592 of 363 breakpoints with ratio changes above 0.20
p_merge  1.00e-22	0.615 of 348 breakpoints with ratio changes above 0.20
p_merge  1.00e-25	0.618 of 338 breakpoints with ratio changes above 0.20
p_merge  1.00e-28	0.624 of 330 breakpoints with ratio changes above 0.20
p_merge  1.00e-31	0.644 of 317 breakpoints with ratio changes above 0.20
p_merge  1.00e-34	0.660 of 303 breakpoints with ratio changes above 0.20
p_merge  1.00e-37	0.671 of 286 breakpoints with ratio changes above 0.20
p_merge  1.00e-40	0.675 of 280 breakpoints with ratio changes above 0.20
p_merge  1.00e-43	0.667 of 273 breakpoints with ratio changes above 0.20
p_merge  1.00e-46	0.658 of 266 breakpoints with ratio changes above 0.20
p_merge  1.00e-49	0.668 of 256 breakpoints with ratio changes above 0.20
p_merge  1.00e-52	0.676 of 244 breakpoints with ratio changes above 0.20
p_merge  1.00e-55	0.688 of 240 breakpoints with ratio changes above 0.20
p_merge  1.00e-58	0.685 of 235 breakpoints with ratio changes above 0.20
p_merge  1.00e-61	0.688 of 224 breakpoints with ratio changes above 0.20
p_merge  1.00e-64	0.679 of 218 breakpoints with ratio changes above 0.20
p_merge  1.00e-67	0.674 of 215 breakpoints with ratio changes above 0.20
p_merge  1.00e-70	0.663 of 208 breakpoints with ratio changes above 0.20
p_merge  1.00e-73	0.667 of 207 breakpoints with ratio changes above 0.20
p_merge  1.00e-76	0.670 of 200 breakpoints with ratio changes above 0.20
p_merge  1.00e-79	0.665 of 197 breakpoints with ratio changes above 0.20
p_merge  1.00e-82	0.663 of 190 breakpoints with ratio changes above 0.20


SegSeq -s test_3023J -t OV-0751_3023J_noCNV_aligned_reads.mat -p 1e-10 -v 0
p_merge  1.00e-13	0.599 of 279 breakpoints with ratio changes above 0.20
p_merge  1.00e-16	0.608 of 260 breakpoints with ratio changes above 0.20
p_merge  1.00e-19	0.622 of 251 breakpoints with ratio changes above 0.20
p_merge  1.00e-22	0.627 of 249 breakpoints with ratio changes above 0.20
p_merge  1.00e-25	0.639 of 241 breakpoints with ratio changes above 0.20
p_merge  1.00e-28	0.651 of 229 breakpoints with ratio changes above 0.20
p_merge  1.00e-31	0.653 of 222 breakpoints with ratio changes above 0.20
p_merge  1.00e-34	0.662 of 216 breakpoints with ratio changes above 0.20
p_merge  1.00e-37	0.667 of 213 breakpoints with ratio changes above 0.20
p_merge  1.00e-40	0.680 of 203 breakpoints with ratio changes above 0.20
p_merge  1.00e-43	0.670 of 194 breakpoints with ratio changes above 0.20
p_merge  1.00e-46	0.677 of 189 breakpoints with ratio changes above 0.20
p_merge  1.00e-49	0.683 of 180 breakpoints with ratio changes above 0.20
p_merge  1.00e-52	0.678 of 174 breakpoints with ratio changes above 0.20
p_merge  1.00e-55	0.673 of 171 breakpoints with ratio changes above 0.20
p_merge  1.00e-58	0.679 of 165 breakpoints with ratio changes above 0.20
p_merge  1.00e-61	0.683 of 164 breakpoints with ratio changes above 0.20
p_merge  1.00e-64	0.692 of 159 breakpoints with ratio changes above 0.20
p_merge  1.00e-67	0.690 of 158 breakpoints with ratio changes above 0.20
p_merge  1.00e-70	0.692 of 156 breakpoints with ratio changes above 0.20
p_merge  1.00e-73	0.688 of 154 breakpoints with ratio changes above 0.20
p_merge  1.00e-76	0.682 of 151 breakpoints with ratio changes above 0.20
p_merge  1.00e-79	0.682 of 151 breakpoints with ratio changes above 0.20
p_merge  1.00e-82	0.682 of 151 breakpoints with ratio changes above 0.20
