function closepair2(probe_fasta,pool_fasta,out_dir,k)

if ~exist('k','var'), k=20; end
if ~ismember(k,[12,16,20,24]), error('Illegal value for k'); end

if ~exist(out_dir,'dir'), mkdir(out_dir); end

cmd = [...
     'unlimit stacksize' ...
     ';unsetenv _dk_inuse'...
     ';use -q .boost-1.38.0'...
     ';unuse -q arachne'...
     ';use -q GCC-4.3'...
     ';/wga/dev/jaffe/Arachne/bin/ClosePair2'...
     ' VERBOSE=True PAIR=' probe_fasta ...
     ' READS=' pool_fasta ...
     ' OUT_DIR=' out_dir ...
     ' K=' num2str(k) ...
     ' REFHEAD=/seq/references/Homo_sapiens_assembly18/v0/Homo_sapiens_assembly18.fasta.lookuptable'...
     ' > ' out_dir '/output'...
  ];

% disp(cmd);
system(cmd);



%     ' VERBOSE=True PAIR=' probe_pair ' OUT_DIR=' out_dir ' K=' num2str(k) ...
%     ' FREEZE_DIR=/wga/scr3/kiran/tcga/tcga-tumor-freeze4-090125 CLFS_SUBDIR=clfs/wg.e4'...
%     ' REFHEAD=/seq/references/Homo_sapiens_assembly18/v0/Homo_sapiens_assembly18.fasta.lookuptable'...


%     'setenv LD_LIBRARY_PATH ' ...
%     '/usr/intel/compiler81/lib:.:/util/gcc-4.3.0/lib64:' ...
%     '/util/gcc-4.3.0/lib/gcc/x86_64-unknown-linux-gnu/4.3.0:/util/gcc-4.3.0/lib/:/util/lib' ...
