function ExtractUnalignedReads(bamfile,max_Ns,min_sumQ,pairmate_mapped_status,output_every_Nth_candidate,outfile,banner)

java_classpath = [...
   '/xchip/tcga/gbm/analysis/lawrence/samtools/trunk/sam-jdk/dist/sam-1.0.jar:'...
   '/home/radon00/lawrence/CancerGenomeAnalysis/trunk/matlab/seq'...
];

cmd = ['"java -classpath ' java_classpath ' ExtractUnalignedReads ' bamfile ' ' ...
       num2str(max_Ns) ' ' num2str(min_sumQ) ' ' num2str(pairmate_mapped_status) ' '...
       num2str(output_every_Nth_candidate) ' ' outfile ...
      '"'];

bsub(cmd,banner);
